#!/usr/bin/env node

const commands = require('./index.js');

// eslint-disable-next-line no-unused-vars
commands.reduce(
  (yargs, { command, describe, builder, handler }) => yargs.command(command, describe, builder, handler),
  require('yargs')
)
  .demandCommand()
  .help()
  .argv;
