#!/usr/bin/env node

process.env.VID_LOGGING = ['0', 'false'].includes(process.env.VID_LOGGING) ? '' : 1;

const { commands } = require('./index.js');

// eslint-disable-next-line no-unused-vars
commands.reduce(
  (yargs, { command, describe, builder, handler }) => yargs.command(command, describe, builder, handler),
  require('yargs')
)
  .demandCommand()
  .help()
  .argv;
